import type { Exercise, EquipmentType, ExperienceLevel, MuscleGroup, EquipmentRequired } from '@/types'

/**
 * MASTER EXERCISE DATABASE (150+ Movements)
 * Covering all muscle groups, equipment types, and movement patterns
 * with step-by-step form instructions, cues, and smart substitution mappings.
 */
export const EXERCISES: Record<string, Exercise> = {
  // ============================================================
  // CHEST (PECTORALS)
  // ============================================================
  flat_bench_press: {
    id: 'flat_bench_press',
    name: 'Barbell Flat Bench Press',
    muscle_groups: ['chest', 'shoulders', 'triceps'],
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders', 'triceps'],
    equipment: ['barbell'],
    is_compound: true,
    difficulty: 'intermediate',
    substitutes: ['dumbbell_bench_press', 'machine_chest_press', 'push_up'],
    instructions: 'Lie flat on the bench, grip bar slightly wider than shoulders, unrack, lower to mid-chest, and press explosively while driving through your feet.',
    instruction_details: {
      setup: 'Set eyes directly beneath the bar. Retract shoulder blades and arch lower back slightly. Plant feet firmly on the floor.',
      execution: 'Unrack bar. Inhale and lower under control until touching the mid-sternum. Tuck elbows at ~45-75 degrees. Drive bar upward to full lockout while exhaling.',
      cues: ['Pinch shoulder blades together', 'Drive heels into the ground', 'Bend the bar with your hands'],
    },
  },
  dumbbell_bench_press: {
    id: 'dumbbell_bench_press',
    name: 'Flat Dumbbell Bench Press',
    muscle_groups: ['chest', 'shoulders', 'triceps'],
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders', 'triceps'],
    equipment: ['dumbbell'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['flat_bench_press', 'machine_chest_press', 'push_up'],
    instructions: 'Press dumbbells from shoulder height with a natural slight inward arc at the top for deep chest contraction.',
    instruction_details: {
      setup: 'Sit on bench edge with dumbbells on knees. Kick dumbbells up as you lie back. Keep feet planted.',
      execution: 'Lower dumbbells until you feel a deep chest stretch. Press up and slightly inward without clanking weights together.',
      cues: ['Control the descent for 2-3 seconds', 'Squeeze inner chest at apex', 'Keep wrists straight above elbows'],
    },
  },
  incline_bench_press: {
    id: 'incline_bench_press',
    name: 'Incline Barbell Bench Press',
    muscle_groups: ['chest', 'shoulders', 'triceps'],
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders', 'triceps'],
    equipment: ['barbell'],
    is_compound: true,
    difficulty: 'intermediate',
    substitutes: ['incline_dumbbell_press', 'incline_machine_press'],
    instructions: 'Set bench to 30-45 degrees to target upper clavicular head of the pectorals.',
    instruction_details: {
      setup: 'Bench angle at 30° to 45°. Grip bar slightly wider than shoulder width. Retract scapula.',
      execution: 'Lower bar smoothly to the upper collarbone area. Press vertically upward to lockout.',
      cues: ['Touch upper chest collarbone', 'Keep elbows at 45 degrees', 'Do not bounce off chest'],
    },
  },
  incline_dumbbell_press: {
    id: 'incline_dumbbell_press',
    name: 'Incline Dumbbell Press',
    muscle_groups: ['chest', 'shoulders', 'triceps'],
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders', 'triceps'],
    equipment: ['dumbbell'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['incline_bench_press', 'incline_push_up', 'incline_cable_flyes'],
    instructions: '30-degree incline press for maximum upper chest hypertrophy and shoulder joint freedom.',
    instruction_details: {
      setup: 'Set bench to 30-degree incline. Kick dumbbells up to starting position at clavicle height.',
      execution: 'Lower dumbbells wide for maximum stretch on upper fibers. Press upward directly over upper chest.',
      cues: ['Chest proud', 'Lead with upper chest fibers', 'Slow eccentric phase'],
    },
  },
  decline_barbell_press: {
    id: 'decline_barbell_press',
    name: 'Decline Barbell Bench Press',
    muscle_groups: ['chest', 'triceps'],
    primary_muscle: 'chest',
    secondary_muscles: ['triceps'],
    equipment: ['barbell'],
    is_compound: true,
    difficulty: 'intermediate',
    substitutes: ['decline_dumbbell_press', 'chest_dips'],
    instructions: 'Targets the lower pectorals with reduced front deltoid strain.',
    instruction_details: {
      setup: 'Hook legs securely in decline bench. Grip bar shoulder-width apart.',
      execution: 'Lower bar to lower chest line. Press upward directly above lower sternum.',
      cues: ['Keep core braced', 'Control bar path carefully', 'Keep wrists neutral'],
    },
  },
  decline_dumbbell_press: {
    id: 'decline_dumbbell_press',
    name: 'Decline Dumbbell Press',
    muscle_groups: ['chest', 'triceps'],
    primary_muscle: 'chest',
    secondary_muscles: ['triceps'],
    equipment: ['dumbbell'],
    is_compound: true,
    difficulty: 'intermediate',
    substitutes: ['decline_barbell_press', 'chest_dips'],
    instructions: 'Lower chest hypertrophy with greater range of motion.',
    instruction_details: {
      setup: 'Lock legs in decline bench, bring dumbbells to chest level.',
      execution: 'Lower with elbows slightly tucked, squeeze chest hard at the top.',
      cues: ['Squeeze lower pecs at contraction', 'Maintain steady tempo'],
    },
  },
  chest_dips: {
    id: 'chest_dips',
    name: 'Chest Dips (Forward Lean)',
    muscle_groups: ['chest', 'triceps', 'shoulders'],
    primary_muscle: 'chest',
    secondary_muscles: ['triceps', 'shoulders'],
    equipment: ['bodyweight'],
    is_compound: true,
    difficulty: 'intermediate',
    substitutes: ['decline_barbell_press', 'cable_flyes_high_to_low', 'push_up'],
    instructions: 'Lean torso forward 30 degrees and flare elbows slightly to emphasize chest over triceps.',
    instruction_details: {
      setup: 'Grip parallel dip bars. Lean chest forward, bend knees with feet behind.',
      execution: 'Lower until upper arms are parallel to floor. Press up through palms squeezing chest.',
      cues: ['Keep chin tucked and chest tilted forward', 'Do not shrug shoulders', 'Flare elbows 30-45 degrees'],
    },
  },
  machine_chest_press: {
    id: 'machine_chest_press',
    name: 'Seated Machine Chest Press',
    muscle_groups: ['chest', 'shoulders', 'triceps'],
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders', 'triceps'],
    equipment: ['machine'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['flat_bench_press', 'dumbbell_bench_press'],
    instructions: 'Controlled seated press allowing deep stretch and peak continuous tension.',
    instruction_details: {
      setup: 'Adjust seat height so handles align with mid-chest. Back flat against pad.',
      execution: 'Press forward smoothly to near lockout. Return under control without letting weights touch stack.',
      cues: ['Drive through the palm heels', 'Keep shoulders pinned back', 'Full stretch at bottom'],
    },
  },
  incline_machine_press: {
    id: 'incline_machine_press',
    name: 'Incline Machine Chest Press',
    muscle_groups: ['chest', 'shoulders'],
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders', 'triceps'],
    equipment: ['machine'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['incline_dumbbell_press', 'incline_bench_press'],
    instructions: 'Upper chest isolation on converging machine track.',
    instruction_details: {
      setup: 'Seat positioned so handles sit at collarbone level.',
      execution: 'Press handles upward along converging arc. Pause for 1 sec at peak squeeze.',
      cues: ['Keep upper back tight against pad', 'Squeeze clavicle fibers'],
    },
  },
  pec_deck_flyes: {
    id: 'pec_deck_flyes',
    name: 'Pec Deck Machine Flyes',
    muscle_groups: ['chest'],
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders'],
    equipment: ['machine'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['cable_crossover_mid', 'dumbbell_flyes'],
    instructions: 'Pure chest isolation with zero tricep involvement.',
    instruction_details: {
      setup: 'Adjust seat so handles/pads are at mid-chest height. Elbows slightly bent.',
      execution: 'Bring arms together in hugging motion. Squeeze chest together for 1 full second.',
      cues: ['Think about touching elbows together', 'Chest high', 'Control the stretch back'],
    },
  },
  cable_crossover_mid: {
    id: 'cable_crossover_mid',
    name: 'Standing Cable Crossover (Mid-Chest)',
    muscle_groups: ['chest'],
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders'],
    equipment: ['cable'],
    is_compound: false,
    difficulty: 'intermediate',
    substitutes: ['pec_deck_flyes', 'dumbbell_flyes'],
    instructions: 'Cables set at chest height for constant peak tension across horizontal adduction.',
    instruction_details: {
      setup: 'Pulleys set at mid-torso height. Step forward into split stance with slight forward lean.',
      execution: 'Bring handles together across chest with soft elbow bend. Cross hands slightly for peak contraction.',
      cues: ['Hug a giant tree trunk', 'Hold peak contraction for 1 second', 'Slow release back'],
    },
  },
  cable_flyes_high_to_low: {
    id: 'cable_flyes_high_to_low',
    name: 'High-to-Low Cable Flyes (Lower Chest)',
    muscle_groups: ['chest'],
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders'],
    equipment: ['cable'],
    is_compound: false,
    difficulty: 'intermediate',
    substitutes: ['chest_dips', 'decline_dumbbell_press'],
    instructions: 'Cables set high, pull down and forward to target lower sternal pec fibers.',
    instruction_details: {
      setup: 'Pulleys set at highest notch. Split stance, slight forward torso tilt.',
      execution: 'Sweep handles downward toward hips. Squeeze lower pecs at the bottom.',
      cues: ['Drive hands down toward your pockets', 'Squeeze bottom pecs hard'],
    },
  },
  cable_flyes_low_to_high: {
    id: 'cable_flyes_low_to_high',
    name: 'Low-to-High Cable Flyes (Upper Chest)',
    muscle_groups: ['chest', 'shoulders'],
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders'],
    equipment: ['cable'],
    is_compound: false,
    difficulty: 'intermediate',
    substitutes: ['incline_dumbbell_press', 'incline_push_up'],
    instructions: 'Cables set low, scoop upward to target clavicular upper chest fibers.',
    instruction_details: {
      setup: 'Pulleys at bottom notch. Palms facing forward and slightly up.',
      execution: 'Scoop handles upward in an arc toward chin/eye level. Hold peak contraction.',
      cues: ['Lead with the inside of your wrists', 'Feel the upper chest pinch at top'],
    },
  },
  dumbbell_flyes: {
    id: 'dumbbell_flyes',
    name: 'Flat Dumbbell Flyes',
    muscle_groups: ['chest'],
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders'],
    equipment: ['dumbbell'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['pec_deck_flyes', 'cable_crossover_mid'],
    instructions: 'Wide arc movement opening the chest cage under controlled dumbbell load.',
    instruction_details: {
      setup: 'Lie on flat bench with dumbbells above chest, slight elbow bend.',
      execution: 'Open arms wide until elbows reach bench height. Squeeze chest to bring weights back up.',
      cues: ['Keep elbow angle locked throughout', 'Focus on the stretch at the bottom'],
    },
  },
  incline_dumbbell_flyes: {
    id: 'incline_dumbbell_flyes',
    name: 'Incline Dumbbell Flyes',
    muscle_groups: ['chest', 'shoulders'],
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders'],
    equipment: ['dumbbell'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['cable_flyes_low_to_high', 'incline_dumbbell_press'],
    instructions: 'Upper chest fly movement performed on a 30-degree incline bench.',
    instruction_details: {
      setup: 'Set bench to 30°. Hold dumbbells aloft with neutral palms.',
      execution: 'Open arms wide in a smooth arc. Pull up and in over upper chest.',
      cues: ['Upper chest stretch at bottom', 'Smooth controlled tempo'],
    },
  },
  push_up: {
    id: 'push_up',
    name: 'Standard Push-Up',
    muscle_groups: ['chest', 'shoulders', 'triceps', 'core'],
    primary_muscle: 'chest',
    secondary_muscles: ['triceps', 'shoulders', 'core'],
    equipment: ['bodyweight'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['flat_bench_press', 'machine_chest_press', 'incline_push_up'],
    instructions: 'The foundational bodyweight upper body pushing movement.',
    instruction_details: {
      setup: 'Hands placed slightly outside shoulder width. Body in a rigid plank line.',
      execution: 'Lower chest to 1 inch above the floor. Push aggressively through palms to full lockout.',
      cues: ['Squeeze glutes and abs tight', 'Elbows at 45 degree angle', 'Do not sag hips'],
    },
  },
  diamond_push_up: {
    id: 'diamond_push_up',
    name: 'Diamond Push-Up (Close Grip)',
    muscle_groups: ['triceps', 'chest', 'shoulders'],
    primary_muscle: 'triceps',
    secondary_muscles: ['chest', 'shoulders'],
    equipment: ['bodyweight'],
    is_compound: true,
    difficulty: 'intermediate',
    substitutes: ['close_grip_bench_press', 'tricep_dips'],
    instructions: 'Hands touching under chest in a diamond shape to emphasize triceps and inner chest.',
    instruction_details: {
      setup: 'Index fingers and thumbs touching to form a diamond directly under sternum.',
      execution: 'Lower chest down to touch your hands. Push up through palms.',
      cues: ['Keep elbows tucked close to ribcage', 'Keep body locked in a plank'],
    },
  },
  incline_push_up: {
    id: 'incline_push_up',
    name: 'Incline Push-Up (Hands Elevated)',
    muscle_groups: ['chest', 'shoulders', 'triceps'],
    primary_muscle: 'chest',
    secondary_muscles: ['triceps', 'shoulders'],
    equipment: ['bodyweight'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['push_up', 'dumbbell_bench_press'],
    instructions: 'Hands elevated on bench or box for beginner-friendly chest conditioning.',
    instruction_details: {
      setup: 'Place hands on a sturdy bench or elevated surface.',
      execution: 'Lower chest to edge of bench and press up.',
      cues: ['Maintain straight spine line', 'Drive through palms'],
    },
  },
  decline_push_up: {
    id: 'decline_push_up',
    name: 'Decline Push-Up (Feet Elevated)',
    muscle_groups: ['chest', 'shoulders', 'triceps'],
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders', 'triceps'],
    equipment: ['bodyweight'],
    is_compound: true,
    difficulty: 'intermediate',
    substitutes: ['incline_bench_press', 'incline_dumbbell_press'],
    instructions: 'Feet elevated on bench to shift emphasis directly onto upper chest and front delts.',
    instruction_details: {
      setup: 'Place toes on bench, hands on the floor shoulder-width apart.',
      execution: 'Lower head and upper chest toward the floor, press up to lockout.',
      cues: ['Brace core to protect lower back', 'Control the descent'],
    },
  },
  landmine_chest_press: {
    id: 'landmine_chest_press',
    name: 'Landmine Chest Press (Single or Double Arm)',
    muscle_groups: ['chest', 'shoulders', 'triceps'],
    primary_muscle: 'chest',
    secondary_muscles: ['shoulders', 'triceps'],
    equipment: ['barbell'],
    is_compound: true,
    difficulty: 'intermediate',
    substitutes: ['incline_dumbbell_press', 'cable_flyes_low_to_high'],
    instructions: 'Angled pressing movement delivering upper chest contraction with zero shoulder impingement.',
    instruction_details: {
      setup: 'Place barbell end in landmine swivel. Stand with slight forward lean holding sleeve.',
      execution: 'Press sleeve upward and inward across chest. Squeeze upper chest at top.',
      cues: ['Keep elbow tucked', 'Drive with upper pectoral fibers'],
    },
  },
  hex_press: {
    id: 'hex_press',
    name: 'Dumbbell Hex Press (Champagne Press)',
    muscle_groups: ['chest', 'triceps'],
    primary_muscle: 'chest',
    secondary_muscles: ['triceps'],
    equipment: ['dumbbell'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['dumbbell_bench_press', 'pec_deck_flyes'],
    instructions: 'Squeeze two dumbbells together as hard as possible while pressing up and down.',
    instruction_details: {
      setup: 'Lie on flat or slight incline bench holding dumbbells touching together above chest.',
      execution: 'Actively crush dumbbells together inward as you lower to chest and press up.',
      cues: ['Continuous inward isometric crush', 'Feel intense inner chest burn'],
    },
  },

  // ============================================================
  // BACK (LATS, RHOMBOIDS, TRAPS, ERECTORS)
  // ============================================================
  conventional_deadlift: {
    id: 'conventional_deadlift',
    name: 'Conventional Barbell Deadlift',
    muscle_groups: ['back', 'hamstrings', 'glutes', 'traps', 'core'],
    primary_muscle: 'back',
    secondary_muscles: ['hamstrings', 'glutes', 'traps', 'forearms'],
    equipment: ['barbell'],
    is_compound: true,
    difficulty: 'advanced',
    substitutes: ['sumo_deadlift', 'romanian_deadlift', 'rack_pulls', 'trap_bar_deadlift'],
    instructions: 'The king of posterior chain exercises. Lift the loaded barbell from floor to hip lockout.',
    instruction_details: {
      setup: 'Feet hip-width, bar over midfoot. Bend over and grip bar outside knees. Drop hips until shins touch bar. Pull chest up.',
      execution: 'Take a deep breath and brace core. Push the floor away through midfoot. Lock out hips and knees simultaneously.',
      cues: ['Push the floor away', 'Keep bar glued to shins and thighs', 'Lock lats down like putting them in back pockets'],
    },
  },
  sumo_deadlift: {
    id: 'sumo_deadlift',
    name: 'Sumo Barbell Deadlift',
    muscle_groups: ['glutes', 'hamstrings', 'quads', 'back', 'traps'],
    primary_muscle: 'glutes',
    secondary_muscles: ['hamstrings', 'quads', 'back'],
    equipment: ['barbell'],
    is_compound: true,
    difficulty: 'advanced',
    substitutes: ['conventional_deadlift', 'trap_bar_deadlift'],
    instructions: 'Wide stance deadlift with more upright torso, targeting hips, glutes, and adductors.',
    instruction_details: {
      setup: 'Take a very wide stance with toes pointed outward ~45°. Grip bar inside legs.',
      execution: 'Spread the floor with your feet. Drive hips forward into the bar at lockout.',
      cues: ['Keep chest proud and upright', 'Open hips and spread knees wide', 'Drive through heel/midfoot'],
    },
  },
  barbell_bent_over_row: {
    id: 'barbell_bent_over_row',
    name: 'Barbell Bent-Over Row (Overhand)',
    muscle_groups: ['back', 'biceps', 'shoulders', 'traps'],
    primary_muscle: 'back',
    secondary_muscles: ['biceps', 'traps', 'shoulders'],
    equipment: ['barbell'],
    is_compound: true,
    difficulty: 'intermediate',
    substitutes: ['t_bar_row', 'single_arm_dumbbell_row', 'seated_cable_row'],
    instructions: 'Hinge forward at 45 degrees and row the barbell into the lower ribcage.',
    instruction_details: {
      setup: 'Hinge hips back to 45° angle. Grip bar slightly wider than shoulder width.',
      execution: 'Pull bar toward belly button leading with elbows. Squeeze scapulae together at top.',
      cues: ['Pull with your elbows, not hands', 'Do not bounce torso', 'Squeeze lats and rhomboids at top'],
    },
  },
  pendlay_row: {
    id: 'pendlay_row',
    name: 'Pendlay Row (From Dead Stop Floor)',
    muscle_groups: ['back', 'traps', 'biceps', 'core'],
    primary_muscle: 'back',
    secondary_muscles: ['traps', 'biceps', 'core'],
    equipment: ['barbell'],
    is_compound: true,
    difficulty: 'advanced',
    substitutes: ['barbell_bent_over_row', 't_bar_row'],
    instructions: 'Strict barbell row starting from a dead stop on the floor each rep.',
    instruction_details: {
      setup: 'Torso strictly parallel to floor. Bar rests on ground between reps.',
      execution: 'Explosively pull bar to lower sternum without raising torso angle.',
      cues: ['Dead stop on floor each rep', 'Zero torso momentum', 'Explosive pull'],
    },
  },
  t_bar_row: {
    id: 't_bar_row',
    name: 'T-Bar Row (Chest Supported or Free)',
    muscle_groups: ['back', 'traps', 'biceps'],
    primary_muscle: 'back',
    secondary_muscles: ['traps', 'biceps'],
    equipment: ['barbell', 'machine'],
    is_compound: true,
    difficulty: 'intermediate',
    substitutes: ['barbell_bent_over_row', 'seated_cable_row', 'chest_supported_dumbbell_row'],
    instructions: 'Close neutral grip row for tremendous mid-back thickness and lat loading.',
    instruction_details: {
      setup: 'Straddle the bar with neutral handle attachment. Hinge hips back at 45°.',
      execution: 'Pull weight toward upper abdomen. Squeeze shoulder blades hard.',
      cues: ['Keep spine neutral', 'Drive elbows back behind torso'],
    },
  },
  single_arm_dumbbell_row: {
    id: 'single_arm_dumbbell_row',
    name: 'Single-Arm Dumbbell Row',
    muscle_groups: ['back', 'biceps', 'core'],
    primary_muscle: 'back',
    secondary_muscles: ['biceps', 'core'],
    equipment: ['dumbbell'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['barbell_bent_over_row', 'seated_cable_row'],
    instructions: 'One hand and knee on bench, pull dumbbell to hip with full lat stretch and contraction.',
    instruction_details: {
      setup: 'Place one knee and hand on flat bench. Torso flat and parallel to ground.',
      execution: 'Pull dumbbell back toward hip in an arc. Lower under full control into deep stretch.',
      cues: ['Pull elbow toward hip pocket', 'Get a full lat stretch at the bottom', 'Do not rotate torso'],
    },
  },
  chest_supported_dumbbell_row: {
    id: 'chest_supported_dumbbell_row',
    name: 'Chest-Supported Incline Dumbbell Row',
    muscle_groups: ['back', 'traps', 'shoulders', 'biceps'],
    primary_muscle: 'back',
    secondary_muscles: ['traps', 'biceps'],
    equipment: ['dumbbell'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['t_bar_row', 'seated_cable_row'],
    instructions: 'Prone on 30-degree incline bench to eliminate lower back fatigue and isolate upper back.',
    instruction_details: {
      setup: 'Lie chest-down on 30° incline bench with dumbbells hanging naturally.',
      execution: 'Row dumbbells up leading with elbows. Pinch shoulder blades together hard.',
      cues: ['Strict upper back isolation', 'Zero momentum', 'Pause for 1 sec at top'],
    },
  },
  lat_pulldown_wide: {
    id: 'lat_pulldown_wide',
    name: 'Wide-Grip Lat Pulldown',
    muscle_groups: ['back', 'biceps', 'shoulders'],
    primary_muscle: 'back',
    secondary_muscles: ['biceps', 'shoulders'],
    equipment: ['cable'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['pull_up', 'close_grip_lat_pulldown', 'underhand_lat_pulldown'],
    instructions: 'Sit facing cable stack with thigh pads locked. Pull wide bar smoothly to upper clavicle.',
    instruction_details: {
      setup: 'Thigh pads snug. Grip bar just outside the outer bend with overhand grip.',
      execution: 'Lean back 10-15°. Drive elbows down and back to bring bar to upper chest.',
      cues: ['Lead with elbows straight down', 'Chest high', 'Do not swing backwards excessively'],
    },
  },
  close_grip_lat_pulldown: {
    id: 'close_grip_lat_pulldown',
    name: 'Close-Grip V-Bar Lat Pulldown',
    muscle_groups: ['back', 'biceps'],
    primary_muscle: 'back',
    secondary_muscles: ['biceps'],
    equipment: ['cable'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['lat_pulldown_wide', 'pull_up_neutral'],
    instructions: 'Using V-bar attachment to maximize lower lat stretch and range of motion.',
    instruction_details: {
      setup: 'Attach V-handle. Sit tall with chest up.',
      execution: 'Pull handle down to upper chest, squeezing lats and lower traps.',
      cues: ['Full stretch at top', 'Drive elbows straight into sides'],
    },
  },
  underhand_lat_pulldown: {
    id: 'underhand_lat_pulldown',
    name: 'Underhand Reverse-Grip Lat Pulldown',
    muscle_groups: ['back', 'biceps'],
    primary_muscle: 'back',
    secondary_muscles: ['biceps'],
    equipment: ['cable'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['chin_up', 'close_grip_lat_pulldown'],
    instructions: 'Supinated grip increases bicep leverage and lower lat recruitment.',
    instruction_details: {
      setup: 'Grip straight bar shoulder-width apart with palms facing you.',
      execution: 'Pull bar down to sternum keeping elbows close to ribs.',
      cues: ['Tuck elbows tight to torso', 'Deep lat squeeze at bottom'],
    },
  },
  pull_up: {
    id: 'pull_up',
    name: 'Standard Pull-Up (Overhand)',
    muscle_groups: ['back', 'biceps', 'core', 'shoulders'],
    primary_muscle: 'back',
    secondary_muscles: ['biceps', 'core', 'shoulders'],
    equipment: ['bodyweight', 'pull_up_bar'],
    is_compound: true,
    difficulty: 'intermediate',
    substitutes: ['lat_pulldown_wide', 'chin_up', 'inverted_row'],
    instructions: 'Grip bar overhand slightly wider than shoulders and pull chin over bar.',
    instruction_details: {
      setup: 'Dead hang from pull-up bar with overhand grip. Engage core.',
      execution: 'Drive elbows down to pull collarbone up toward the bar. Lower under control to dead hang.',
      cues: ['Drive elbows to ribs', 'No kicking or kipping', 'Full dead hang at bottom'],
    },
  },
  chin_up: {
    id: 'chin_up',
    name: 'Chin-Up (Underhand Grip)',
    muscle_groups: ['biceps', 'back', 'core'],
    primary_muscle: 'back',
    secondary_muscles: ['biceps', 'core'],
    equipment: ['bodyweight', 'pull_up_bar'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['pull_up', 'underhand_lat_pulldown', 'standing_barbell_curl'],
    instructions: 'Underhand shoulder-width grip for tremendous bicep and lat power.',
    instruction_details: {
      setup: 'Palms facing you, shoulder width apart on pull-up bar.',
      execution: 'Pull until chin clears the bar comfortably. Lower down smoothly.',
      cues: ['Squeeze biceps at the top', 'Controlled 2-second descent'],
    },
  },
  pull_up_neutral: {
    id: 'pull_up_neutral',
    name: 'Neutral-Grip Pull-Up',
    muscle_groups: ['back', 'biceps', 'forearms'],
    primary_muscle: 'back',
    secondary_muscles: ['biceps', 'forearms'],
    equipment: ['bodyweight', 'pull_up_bar'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['pull_up', 'close_grip_lat_pulldown'],
    instructions: 'Palms facing each other on parallel bars — easiest on the shoulder joints.',
    instruction_details: {
      setup: 'Grip parallel handles in neutral grip.',
      execution: 'Pull up smoothly until chest reaches handle height.',
      cues: ['Chest to handles', 'Full extension at bottom'],
    },
  },
  seated_cable_row: {
    id: 'seated_cable_row',
    name: 'Seated Cable Row (Close Grip)',
    muscle_groups: ['back', 'traps', 'biceps', 'shoulders'],
    primary_muscle: 'back',
    secondary_muscles: ['traps', 'biceps'],
    equipment: ['cable'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['barbell_bent_over_row', 't_bar_row', 'single_arm_dumbbell_row'],
    instructions: 'Sit with knees slightly bent. Pull handle to abdomen while maintaining upright spine.',
    instruction_details: {
      setup: 'Feet on platform with knees soft. Sit upright with chest proud.',
      execution: 'Pull handle into lower belly button, squeezing mid-back and lats.',
      cues: ['Do not round lower back on the stretch', 'Pinch shoulder blades together', 'Elbows past torso'],
    },
  },
  seated_wide_cable_row: {
    id: 'seated_wide_cable_row',
    name: 'Seated Cable Row (Wide Overhand Grip)',
    muscle_groups: ['back', 'traps', 'shoulders'],
    primary_muscle: 'back',
    secondary_muscles: ['traps', 'shoulders'],
    equipment: ['cable'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['seated_cable_row', 'face_pulls'],
    instructions: 'Wide grip with flared elbows to isolate rear delts, rhomboids, and mid-traps.',
    instruction_details: {
      setup: 'Attach wide lat bar or multi-grip attachment. Overhand grip.',
      execution: 'Pull bar to upper abdomen with elbows flared at ~60-70 degrees.',
      cues: ['Focus on rear delts and mid-traps squeeze', 'Hold contraction for 1 sec'],
    },
  },
  straight_arm_pulldown: {
    id: 'straight_arm_pulldown',
    name: 'Straight-Arm Cable Pulldown (Lat Sweep)',
    muscle_groups: ['back', 'core'],
    primary_muscle: 'back',
    secondary_muscles: ['core'],
    equipment: ['cable'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['dumbbell_pullover', 'lat_pulldown_wide'],
    instructions: 'Pure lat isolation movement without bicep involvement.',
    instruction_details: {
      setup: 'High pulley with rope or straight bar. Step back with slight forward hip hinge.',
      execution: 'Keeping arms straight with slight elbow bend, sweep bar down in an arc to touch thighs.',
      cues: ['Think of pushing your hands into your thighs', 'Squeeze lats at bottom', 'Feel stretch at eye level'],
    },
  },
  dumbbell_pullover: {
    id: 'dumbbell_pullover',
    name: 'Dumbbell Pullover (Lats & Serratus)',
    muscle_groups: ['back', 'chest', 'core'],
    primary_muscle: 'back',
    secondary_muscles: ['chest', 'core'],
    equipment: ['dumbbell'],
    is_compound: true,
    difficulty: 'intermediate',
    substitutes: ['straight_arm_pulldown'],
    instructions: 'Lie across bench with shoulders supported, lower dumbbell behind head for huge ribcage and lat stretch.',
    instruction_details: {
      setup: 'Upper back resting across a flat bench, hips low. Hold dumbbell with diamond grip over chest.',
      execution: 'Lower dumbbell back over head until arms are aligned with torso. Pull back over chest.',
      cues: ['Keep hips down for maximum lat stretch', 'Slight bend in elbows locked throughout'],
    },
  },
  rack_pulls: {
    id: 'rack_pulls',
    name: 'Barbell Rack Pulls (Knee Height)',
    muscle_groups: ['back', 'traps', 'glutes', 'forearms'],
    primary_muscle: 'back',
    secondary_muscles: ['traps', 'forearms', 'glutes'],
    equipment: ['barbell'],
    is_compound: true,
    difficulty: 'intermediate',
    substitutes: ['conventional_deadlift', 'barbell_shrugs'],
    instructions: 'Deadlift lockouts starting from power rack pins set at or just below knee level.',
    instruction_details: {
      setup: 'Bar resting on rack pins at knee height. Grip bar overhand or mixed grip.',
      execution: 'Drive hips forward into bar, squeezing upper back and traps hard at lockout.',
      cues: ['Massive trap and spinal erector loading', 'Lockout hips firmly'],
    },
  },
  hyperextensions: {
    id: 'hyperextensions',
    name: 'Hyperextensions (Back Extensions 45°)',
    muscle_groups: ['back', 'glutes', 'hamstrings'],
    primary_muscle: 'back',
    secondary_muscles: ['glutes', 'hamstrings'],
    equipment: ['bodyweight'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['good_mornings', 'romanian_deadlift'],
    instructions: '45-degree hyperextension bench targeting spinal erectors, glutes, and hamstrings.',
    instruction_details: {
      setup: 'Adjust pad so top of pad sits just below hip crease.',
      execution: 'Hinge forward at hips until lower back stretches. Rise back up to straight alignment.',
      cues: ['Do not hyperextend spine excessively past straight line', 'Squeeze glutes at top'],
    },
  },
  good_mornings: {
    id: 'good_mornings',
    name: 'Barbell Good Mornings',
    muscle_groups: ['hamstrings', 'glutes', 'back'],
    primary_muscle: 'hamstrings',
    secondary_muscles: ['glutes', 'back'],
    equipment: ['barbell'],
    is_compound: true,
    difficulty: 'advanced',
    substitutes: ['romanian_deadlift', 'hyperextensions'],
    instructions: 'Barbell across upper back, hinge at hips to push glutes backward with soft knees.',
    instruction_details: {
      setup: 'Barbell in low or high bar position on upper back. Stance shoulder width.',
      execution: 'Hinge hips backwards until torso is near parallel to floor. Drive hips forward to stand.',
      cues: ['Soft knees', 'Keep lower back tightly arched and core braced'],
    },
  },
  inverted_row: {
    id: 'inverted_row',
    name: 'Inverted Row (Australian Pull-Up)',
    muscle_groups: ['back', 'biceps', 'core', 'shoulders'],
    primary_muscle: 'back',
    secondary_muscles: ['biceps', 'core'],
    equipment: ['bodyweight'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['barbell_bent_over_row', 'pull_up'],
    instructions: 'Bodyweight horizontal pulling movement under a smith machine bar or gymnastics rings.',
    instruction_details: {
      setup: 'Set bar at waist height in rack. Hang underneath with heels on the floor.',
      execution: 'Pull chest up to touch the bar. Keep body in rigid plank.',
      cues: ['Keep glutes clenched', 'Touch sternum to bar'],
    },
  },

  // ============================================================
  // SHOULDERS & DELTOIDS (FRONT, SIDE, REAR) & TRAPS
  // ============================================================
  overhead_press: {
    id: 'overhead_press',
    name: 'Standing Barbell Overhead Press (OHP)',
    muscle_groups: ['shoulders', 'triceps', 'core', 'traps'],
    primary_muscle: 'shoulders',
    secondary_muscles: ['triceps', 'core', 'traps'],
    equipment: ['barbell'],
    is_compound: true,
    difficulty: 'intermediate',
    substitutes: ['seated_dumbbell_shoulder_press', 'arnold_press', 'machine_shoulder_press'],
    instructions: 'Strict standing press from collarbone to overhead lockout.',
    instruction_details: {
      setup: 'Feet shoulder-width, bar resting across front delts/collarbone. Squeeze glutes and abs.',
      execution: 'Press bar vertically upward in a straight line, pulling head back slightly then pushing head forward through the window at lockout.',
      cues: ['Lock out overhead directly over spine', 'Squeeze glutes to protect lower back', 'Keep forearms vertical'],
    },
  },
  seated_dumbbell_shoulder_press: {
    id: 'seated_dumbbell_shoulder_press',
    name: 'Seated Dumbbell Shoulder Press',
    muscle_groups: ['shoulders', 'triceps', 'traps'],
    primary_muscle: 'shoulders',
    secondary_muscles: ['triceps', 'traps'],
    equipment: ['dumbbell'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['overhead_press', 'arnold_press', 'machine_shoulder_press'],
    instructions: 'Seated 75-80 degree back support press for massive deltoid development.',
    instruction_details: {
      setup: 'Sit on bench with back set to ~75-80° (not 90° to avoid impingement). Kick dumbbells up to shoulder level.',
      execution: 'Press dumbbells up in a gentle arc over head to near-lockout. Lower down to ear level.',
      cues: ['Lower until elbows reach parallel or slightly below', 'Do not clank dumbbells together', 'Keep core tight'],
    },
  },
  arnold_press: {
    id: 'arnold_press',
    name: 'Arnold Dumbbell Press',
    muscle_groups: ['shoulders', 'triceps'],
    primary_muscle: 'shoulders',
    secondary_muscles: ['triceps'],
    equipment: ['dumbbell'],
    is_compound: true,
    difficulty: 'intermediate',
    substitutes: ['seated_dumbbell_shoulder_press', 'overhead_press'],
    instructions: 'Invented by Arnold Schwarzenegger — rotates from supinated palms-in to overhead pronated lockout.',
    instruction_details: {
      setup: 'Hold dumbbells in front of shoulders with palms facing you (chin-up position).',
      execution: 'As you press overhead, rotate wrists 180 degrees so palms face forward at the peak.',
      cues: ['Smooth continuous rotation', 'Hits all 3 deltoid heads in one motion'],
    },
  },
  machine_shoulder_press: {
    id: 'machine_shoulder_press',
    name: 'Machine Overhead Shoulder Press',
    muscle_groups: ['shoulders', 'triceps'],
    primary_muscle: 'shoulders',
    secondary_muscles: ['triceps'],
    equipment: ['machine'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['seated_dumbbell_shoulder_press', 'overhead_press'],
    instructions: 'Safe, stable overhead pressing for pure deltoid overload.',
    instruction_details: {
      setup: 'Adjust seat so handles start at ear/jaw level.',
      execution: 'Press handles upward to full extension. Control the 3-second descent.',
      cues: ['Keep spine pressed against pad', 'Constant tension on shoulders'],
    },
  },
  lateral_raise: {
    id: 'lateral_raise',
    name: 'Standing Dumbbell Lateral Raise',
    muscle_groups: ['shoulders'],
    primary_muscle: 'shoulders',
    secondary_muscles: ['traps'],
    equipment: ['dumbbell'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['cable_lateral_raise', 'seated_lateral_raise', 'machine_lateral_raise'],
    instructions: 'Raise dumbbells out to sides to build wide 3D lateral deltoids.',
    instruction_details: {
      setup: 'Stand with slight forward torso tilt. Hold dumbbells at sides with pinkies slightly higher than thumbs.',
      execution: 'Raise arms out to sides in the scapular plane (30° forward) to shoulder height.',
      cues: ['Lead with the elbows', 'Pour the water slightly at the top', 'Do not use body swing'],
    },
  },
  seated_lateral_raise: {
    id: 'seated_lateral_raise',
    name: 'Seated Dumbbell Lateral Raise',
    muscle_groups: ['shoulders'],
    primary_muscle: 'shoulders',
    equipment: ['dumbbell'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['lateral_raise', 'cable_lateral_raise'],
    instructions: 'Seated position completely eliminates leg drive and momentum for pure side delt isolation.',
    instruction_details: {
      setup: 'Sit on end of bench, dumbbells hanging at sides under knees.',
      execution: 'Raise weights out to sides to parallel. Pause for 0.5s at peak.',
      cues: ['Zero momentum', 'Control down for 3 full seconds'],
    },
  },
  cable_lateral_raise: {
    id: 'cable_lateral_raise',
    name: 'Single-Arm Cable Lateral Raise',
    muscle_groups: ['shoulders'],
    primary_muscle: 'shoulders',
    equipment: ['cable'],
    is_compound: false,
    difficulty: 'intermediate',
    substitutes: ['lateral_raise', 'seated_lateral_raise'],
    instructions: 'Low cable pulley provides continuous tension throughout the entire range of motion.',
    instruction_details: {
      setup: 'Set pulley at ankle or knee height. Hold handle across body or behind back.',
      execution: 'Raise arm out and up to shoulder height. Lower under smooth cable resistance.',
      cues: ['Constant tension from 0° to 90°', 'Do not shrug the shoulder'],
    },
  },
  behind_back_cable_lateral_raise: {
    id: 'behind_back_cable_lateral_raise',
    name: 'Behind-the-Back Cable Lateral Raise',
    muscle_groups: ['shoulders'],
    primary_muscle: 'shoulders',
    equipment: ['cable'],
    is_compound: false,
    difficulty: 'intermediate',
    substitutes: ['cable_lateral_raise', 'lateral_raise'],
    instructions: 'Cable running behind the back creates deep stretch on the side delt.',
    instruction_details: {
      setup: 'Cable behind hips at low position. Lean slightly away from stack.',
      execution: 'Raise arm out wide in a gentle arc to shoulder height.',
      cues: ['Feel the stretch behind hip at bottom', 'Smooth controlled tempo'],
    },
  },
  front_dumbbell_raise: {
    id: 'front_dumbbell_raise',
    name: 'Dumbbell Front Raise',
    muscle_groups: ['shoulders'],
    primary_muscle: 'shoulders',
    equipment: ['dumbbell'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['overhead_press', 'cable_front_raise'],
    instructions: 'Raise dumbbells forward to eye level for anterior deltoid isolation.',
    instruction_details: {
      setup: 'Hold dumbbells in front of thighs with overhand grip.',
      execution: 'Raise one or both arms forward to shoulder height with minimal swing.',
      cues: ['Raise until arm is parallel to floor', 'Keep core braced'],
    },
  },
  cable_front_raise: {
    id: 'cable_front_raise',
    name: 'Cable Front Rope Raise',
    muscle_groups: ['shoulders'],
    primary_muscle: 'shoulders',
    equipment: ['cable'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['front_dumbbell_raise', 'overhead_press'],
    instructions: 'Straddle low cable pulley with rope between legs and raise forward to eye level.',
    instruction_details: {
      setup: 'Low pulley with rope attachment between legs, facing away from stack.',
      execution: 'Raise rope handles up and forward to shoulder height.',
      cues: ['Smooth continuous tension', 'No backward lean'],
    },
  },
  face_pulls: {
    id: 'face_pulls',
    name: 'Cable Face Pulls (with External Rotation)',
    muscle_groups: ['shoulders', 'traps', 'back'],
    primary_muscle: 'shoulders',
    secondary_muscles: ['traps', 'back'],
    equipment: ['cable'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['reverse_pec_deck', 'bent_over_rear_delt_flyes'],
    instructions: 'Pulls rope to forehead with elbows high and thumbs pointing backward for rear delts & rotator cuff.',
    instruction_details: {
      setup: 'Set rope attachment at eye height on cable stack. Grip rope with thumbs pointing toward you.',
      execution: 'Pull rope toward nose/forehead, separating the rope ends and rotating hands back like a double bicep pose.',
      cues: ['Pull hands apart at your temples', 'High elbows', 'Squeeze rear delts and upper traps'],
    },
  },
  reverse_pec_deck: {
    id: 'reverse_pec_deck',
    name: 'Reverse Pec Deck Flyes (Rear Delts)',
    muscle_groups: ['shoulders', 'traps'],
    primary_muscle: 'shoulders',
    secondary_muscles: ['traps'],
    equipment: ['machine'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['face_pulls', 'bent_over_rear_delt_flyes'],
    instructions: 'Sit facing machine chest-in and push handles backward in a horizontal arc.',
    instruction_details: {
      setup: 'Chest against pad, handles at shoulder height with neutral or pronated grip.',
      execution: 'Push handles back with slight elbow bend. Squeeze rear delts at peak.',
      cues: ['Do not shrug traps', 'Focus on rear shoulder cap contraction'],
    },
  },
  bent_over_rear_delt_flyes: {
    id: 'bent_over_rear_delt_flyes',
    name: 'Bent-Over Dumbbell Rear Delt Flyes',
    muscle_groups: ['shoulders', 'traps'],
    primary_muscle: 'shoulders',
    secondary_muscles: ['traps'],
    equipment: ['dumbbell'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['reverse_pec_deck', 'face_pulls'],
    instructions: 'Hinged forward at hips or seated on bench chest-to-thighs, fly dumbbells outward.',
    instruction_details: {
      setup: 'Hinge forward until torso is parallel to ground (or seated on bench leaning forward).',
      execution: 'Raise dumbbells wide in a T-shape leading with pinkies.',
      cues: ['Lead with pinkies', 'Squeeze back of shoulders', 'Do not jerk torso'],
    },
  },
  barbell_shrugs: {
    id: 'barbell_shrugs',
    name: 'Barbell Shrugs (Trapezius)',
    muscle_groups: ['traps', 'shoulders', 'forearms'],
    primary_muscle: 'traps',
    secondary_muscles: ['forearms'],
    equipment: ['barbell'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['dumbbell_shrugs', 'rack_pulls'],
    instructions: 'Elevate shoulders directly toward ears with heavy barbell load.',
    instruction_details: {
      setup: 'Hold barbell with shoulder-width overhand grip in front of thighs.',
      execution: 'Shrug shoulders straight up toward ears. Hold peak squeeze for 1 full second. Lower smoothly.',
      cues: ['Straight up and down — do not roll shoulders', 'Hold for 1 sec at top'],
    },
  },
  dumbbell_shrugs: {
    id: 'dumbbell_shrugs',
    name: 'Dumbbell Shrugs',
    muscle_groups: ['traps', 'forearms'],
    primary_muscle: 'traps',
    secondary_muscles: ['forearms'],
    equipment: ['dumbbell'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['barbell_shrugs'],
    instructions: 'Dumbbells at sides allows completely natural neutral grip and shoulder elevation.',
    instruction_details: {
      setup: 'Hold heavy dumbbells at sides in neutral grip.',
      execution: 'Elevate shoulders as high as possible toward ears. Pause at peak.',
      cues: ['No arm bending', 'Pure trapezius contraction'],
    },
  },
  upright_row: {
    id: 'upright_row',
    name: 'EZ-Bar / Cable Upright Row',
    muscle_groups: ['shoulders', 'traps', 'biceps'],
    primary_muscle: 'shoulders',
    secondary_muscles: ['traps', 'biceps'],
    equipment: ['barbell', 'cable'],
    is_compound: true,
    difficulty: 'intermediate',
    substitutes: ['lateral_raise', 'face_pulls'],
    instructions: 'Wide-grip upright pull to mid-chest for side delts and upper traps.',
    instruction_details: {
      setup: 'Grip bar shoulder-width or wider (avoid close grip to protect wrists/shoulders).',
      execution: 'Pull bar up to chest level leading with high elbows.',
      cues: ['Keep elbows above wrists at all times', 'Pull bar close to body'],
    },
  },

  // ============================================================
  // BICEPS & FOREARMS
  // ============================================================
  standing_barbell_curl: {
    id: 'standing_barbell_curl',
    name: 'Standing Barbell Bicep Curl',
    muscle_groups: ['biceps', 'forearms'],
    primary_muscle: 'biceps',
    secondary_muscles: ['forearms'],
    equipment: ['barbell'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['ez_bar_curl', 'standing_dumbbell_curl', 'cable_bicep_curl'],
    instructions: 'The gold standard for bicep mass and peak strength.',
    instruction_details: {
      setup: 'Stand shoulder-width apart holding barbell with underhand shoulder-width grip.',
      execution: 'Curl bar up toward shoulders keeping elbows pinned to sides. Squeeze biceps at peak and lower for 2-3s.',
      cues: ['Keep elbows pinned at your ribs', 'Do not swing hips or lower back', 'Squeeze biceps at top'],
    },
  },
  ez_bar_curl: {
    id: 'ez_bar_curl',
    name: 'EZ-Bar Bicep Curl',
    muscle_groups: ['biceps', 'forearms'],
    primary_muscle: 'biceps',
    secondary_muscles: ['forearms'],
    equipment: ['barbell'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['standing_barbell_curl', 'standing_dumbbell_curl'],
    instructions: 'Angled bar grip relieves wrist and forearm strain during heavy curling.',
    instruction_details: {
      setup: 'Grip EZ-bar on the inner angled grips.',
      execution: 'Curl bar up smoothly. Lower with full control.',
      cues: ['Keep elbows stationary', 'Full extension at the bottom without hyperextending'],
    },
  },
  standing_dumbbell_curl: {
    id: 'standing_dumbbell_curl',
    name: 'Standing Alternating Dumbbell Curl (with Supination)',
    muscle_groups: ['biceps', 'forearms'],
    primary_muscle: 'biceps',
    secondary_muscles: ['forearms'],
    equipment: ['dumbbell'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['incline_dumbbell_curl', 'standing_barbell_curl'],
    instructions: 'Start in neutral hammer position, then supinate wrist outward at top for peak bicep recruitment.',
    instruction_details: {
      setup: 'Hold dumbbells at sides with palms facing inwards.',
      execution: 'Curl up one arm at a time, turning palms up and pinkies outward as you reach the top.',
      cues: ['Turn pinky up at the peak (supination)', 'Lock elbows in place', 'Controlled descent'],
    },
  },
  incline_dumbbell_curl: {
    id: 'incline_dumbbell_curl',
    name: 'Incline Dumbbell Curl (Long Head Stretch)',
    muscle_groups: ['biceps'],
    primary_muscle: 'biceps',
    equipment: ['dumbbell'],
    is_compound: false,
    difficulty: 'intermediate',
    substitutes: ['standing_dumbbell_curl', 'preacher_curl'],
    instructions: 'Seated on 45-degree incline with arms hanging back for maximum long head stretch.',
    instruction_details: {
      setup: 'Set bench to 45° angle. Lie back with arms hanging vertically behind torso.',
      execution: 'Curl dumbbells up while keeping elbows pointed toward the floor. Squeeze at top.',
      cues: ['Keep shoulders back and elbows pointed down', 'Unrivaled stretch on bicep long head'],
    },
  },
  hammer_curls: {
    id: 'hammer_curls',
    name: 'Dumbbell Hammer Curls (Brachialis & Forearms)',
    muscle_groups: ['biceps', 'forearms'],
    primary_muscle: 'biceps',
    secondary_muscles: ['forearms'],
    equipment: ['dumbbell'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['rope_cable_hammer_curl', 'cross_body_hammer_curl'],
    instructions: 'Neutral palms-facing-inward grip builds arm thickness and forearm size.',
    instruction_details: {
      setup: 'Stand holding dumbbells with palms facing each other throughout the movement.',
      execution: 'Curl weights up toward shoulder height keeping palms strictly neutral.',
      cues: ['Like swinging a hammer', 'Keeps tension on brachialis for arm width', 'No hip swing'],
    },
  },
  cross_body_hammer_curl: {
    id: 'cross_body_hammer_curl',
    name: 'Cross-Body Dumbbell Hammer Curl',
    muscle_groups: ['biceps', 'forearms'],
    primary_muscle: 'biceps',
    secondary_muscles: ['forearms'],
    equipment: ['dumbbell'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['hammer_curls'],
    instructions: 'Curl dumbbell across torso toward opposite shoulder to target the brachialis.',
    instruction_details: {
      setup: 'Dumbbell at side in neutral grip.',
      execution: 'Curl weight across chest towards opposite collarbone.',
      cues: ['Keep palm facing chest', 'Squeeze outer bicep peak'],
    },
  },
  preacher_curl: {
    id: 'preacher_curl',
    name: 'EZ-Bar / Machine Preacher Curl',
    muscle_groups: ['biceps'],
    primary_muscle: 'biceps',
    equipment: ['barbell', 'machine'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['spider_curl', 'concentration_curl'],
    instructions: 'Arms locked against slanted preacher pad eliminates any shoulder cheating.',
    instruction_details: {
      setup: 'Armpits nestled comfortably against top of preacher pad. Grip EZ-bar shoulder width.',
      execution: 'Curl bar up until forearms are near vertical. Lower under strict control until arms are almost straight.',
      cues: ['Do not hyperextend elbows at bottom', 'Keep upper arms glued to the pad'],
    },
  },
  concentration_curl: {
    id: 'concentration_curl',
    name: 'Seated Concentration Curl',
    muscle_groups: ['biceps'],
    primary_muscle: 'biceps',
    equipment: ['dumbbell'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['preacher_curl', 'spider_curl'],
    instructions: 'Elbow braced against inner thigh for ultra-strict single-arm bicep peaking.',
    instruction_details: {
      setup: 'Sit on bench edge, legs spread. Brace back of elbow against inside of same-side thigh.',
      execution: 'Curl dumbbell up to chin height. Squeeze bicep as hard as possible for 1s.',
      cues: ['Zero torso swing', 'Total isolated bicep peak focus'],
    },
  },
  cable_bicep_curl: {
    id: 'cable_bicep_curl',
    name: 'Standing Cable Bicep Curl',
    muscle_groups: ['biceps', 'forearms'],
    primary_muscle: 'biceps',
    secondary_muscles: ['forearms'],
    equipment: ['cable'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['standing_barbell_curl', 'ez_bar_curl'],
    instructions: 'Low cable pulley provides smooth continuous tension throughout the entire curve.',
    instruction_details: {
      setup: 'Low pulley with straight or EZ-curl bar. Step back slightly.',
      execution: 'Curl bar to chin keeping elbows pinned to sides.',
      cues: ['Constant tension even at top and bottom', 'Slow eccentric phase'],
    },
  },
  spider_curl: {
    id: 'spider_curl',
    name: 'Incline Bench Spider Curl (Short Head)',
    muscle_groups: ['biceps'],
    primary_muscle: 'biceps',
    equipment: ['barbell', 'dumbbell'],
    is_compound: false,
    difficulty: 'intermediate',
    substitutes: ['preacher_curl', 'concentration_curl'],
    instructions: 'Chest-down on 45° incline bench with arms hanging vertically forward for peak short head tension.',
    instruction_details: {
      setup: 'Lie chest-down on incline bench, arms hanging straight down in front of torso.',
      execution: 'Curl bar/dumbbells up toward nose without letting elbows swing back.',
      cues: ['Keep elbows forward', 'Peak contraction at the top'],
    },
  },
  bicep_21s: {
    id: 'bicep_21s',
    name: 'Barbell Bicep 21s',
    muscle_groups: ['biceps', 'forearms'],
    primary_muscle: 'biceps',
    secondary_muscles: ['forearms'],
    equipment: ['barbell'],
    is_compound: false,
    difficulty: 'intermediate',
    substitutes: ['standing_barbell_curl'],
    instructions: '7 bottom half reps + 7 top half reps + 7 full range reps = maximum pump.',
    instruction_details: {
      setup: 'Moderate weight on barbell or EZ bar.',
      execution: 'Perform 7 reps from bottom to 90°, then 7 reps from 90° to top, then 7 full reps without stopping.',
      cues: ['Strict form', 'No resting between the 7-rep stages'],
    },
  },
  reverse_curl: {
    id: 'reverse_curl',
    name: 'Reverse-Grip EZ-Bar Curl (Brachioradialis)',
    muscle_groups: ['forearms', 'biceps'],
    primary_muscle: 'forearms',
    secondary_muscles: ['biceps'],
    equipment: ['barbell'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['hammer_curls'],
    instructions: 'Overhand grip curl builds upper forearm brachioradialis and grip strength.',
    instruction_details: {
      setup: 'Hold EZ-bar with overhand palms-down grip.',
      execution: 'Curl bar upward keeping wrists locked in neutral/straight alignment.',
      cues: ['Keep wrists straight', 'Feel burn in upper forearms'],
    },
  },
  wrist_curls: {
    id: 'wrist_curls',
    name: 'Barbell / Dumbbell Wrist Curls',
    muscle_groups: ['forearms'],
    primary_muscle: 'forearms',
    equipment: ['barbell', 'dumbbell'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['farmers_walk'],
    instructions: 'Forearms rested on bench or knees, curl wrists upward to build forearm flexors.',
    instruction_details: {
      setup: 'Forearms flat on bench with wrists hanging off edge holding bar with underhand grip.',
      execution: 'Let bar roll down to fingers, then curl fingers and wrists all the way up.',
      cues: ['Full stretch and contraction in wrist flexors'],
    },
  },

  // ============================================================
  // TRICEPS
  // ============================================================
  tricep_pushdown: {
    id: 'tricep_pushdown',
    name: 'Cable Tricep Pushdown (Straight / V-Bar)',
    muscle_groups: ['triceps'],
    primary_muscle: 'triceps',
    equipment: ['cable'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['rope_pushdown', 'skull_crushers', 'tricep_dips'],
    instructions: 'Pin elbows to ribs and press down to full tricep lockout.',
    instruction_details: {
      setup: 'High cable pulley with straight bar or V-bar. Slight forward torso hinge.',
      execution: 'Press bar down until arms are completely straight and triceps contract. Return to 90° at elbow.',
      cues: ['Keep elbows glued to ribs', 'Do not let shoulders roll forward', 'Lock out hard at bottom'],
    },
  },
  rope_pushdown: {
    id: 'rope_pushdown',
    name: 'Cable Rope Tricep Pushdown',
    muscle_groups: ['triceps'],
    primary_muscle: 'triceps',
    equipment: ['cable'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['tricep_pushdown', 'overhead_tricep_extension'],
    instructions: 'Spread the rope ends apart at the bottom to maximize lateral tricep head contraction.',
    instruction_details: {
      setup: 'High cable with rope attachment. Chest up, elbows tucked at sides.',
      execution: 'Push rope down and flare ends outward past hips at the bottom lockout.',
      cues: ['Spread rope ends apart at bottom', 'Hold peak contraction for 1s'],
    },
  },
  skull_crushers: {
    id: 'skull_crushers',
    name: 'EZ-Bar Skull Crushers (Lying Tricep Extension)',
    muscle_groups: ['triceps'],
    primary_muscle: 'triceps',
    equipment: ['barbell'],
    is_compound: false,
    difficulty: 'intermediate',
    substitutes: ['dumbbell_skull_crushers', 'overhead_tricep_extension', 'close_grip_bench_press'],
    instructions: 'Lie on flat bench, lower EZ-bar toward forehead or crown of head, and extend back to vertical.',
    instruction_details: {
      setup: 'Lie on flat bench holding EZ-bar above chest with narrow overhand grip. Tilt arms back ~10°.',
      execution: 'Bend only at elbows to lower bar toward top of forehead. Press back to starting angled lockout.',
      cues: ['Keep elbows tucked in — do not flare out wide', 'Maintain 10° backward arm tilt for constant tension'],
    },
  },
  dumbbell_skull_crushers: {
    id: 'dumbbell_skull_crushers',
    name: 'Lying Dumbbell Skull Crushers (Neutral Grip)',
    muscle_groups: ['triceps'],
    primary_muscle: 'triceps',
    equipment: ['dumbbell'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['skull_crushers', 'tricep_pushdown'],
    instructions: 'Neutral grip dumbbells lowered past ears for wrist comfort and deeper tricep stretch.',
    instruction_details: {
      setup: 'Lie on bench with dumbbells held in neutral grip above chest.',
      execution: 'Lower dumbbells down on either side of head past ears. Extend arms back up.',
      cues: ['Keep upper arms stationary', 'Deep stretch behind head'],
    },
  },
  overhead_tricep_extension: {
    id: 'overhead_tricep_extension',
    name: 'Overhead Cable / Dumbbell Tricep Extension',
    muscle_groups: ['triceps'],
    primary_muscle: 'triceps',
    equipment: ['cable', 'dumbbell'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['skull_crushers', 'tricep_pushdown', 'tricep_dips'],
    instructions: 'Arms overhead places the long head of the tricep in full stretch for maximum hypertrophy.',
    instruction_details: {
      setup: 'Set cable at hip/shoulder height (or hold dumbbell overhead with both hands). Face away from stack.',
      execution: 'Extend arms forward and overhead to full lockout. Return under control into deep stretch behind head.',
      cues: ['Keep elbows pointing forward', 'Feel the long head stretch behind head', 'Full lockout at extension'],
    },
  },
  close_grip_bench_press: {
    id: 'close_grip_bench_press',
    name: 'Close-Grip Barbell Bench Press',
    muscle_groups: ['triceps', 'chest', 'shoulders'],
    primary_muscle: 'triceps',
    secondary_muscles: ['chest', 'shoulders'],
    equipment: ['barbell'],
    is_compound: true,
    difficulty: 'intermediate',
    substitutes: ['tricep_dips', 'flat_bench_press', 'skull_crushers'],
    instructions: 'Hands placed shoulder-width apart, elbows tucked tight to ribs to overload triceps with heavy weight.',
    instruction_details: {
      setup: 'Lie on flat bench. Grip bar with hands directly shoulder-width apart (not too narrow to protect wrists).',
      execution: 'Lower bar to lower sternum keeping elbows tucked tightly against ribs. Press up through triceps.',
      cues: ['Keep elbows tucked against sides', 'Drive through triceps at lockout', 'Shoulder-width grip'],
    },
  },
  tricep_dips: {
    id: 'tricep_dips',
    name: 'Parallel Bar Tricep Dips (Upright)',
    muscle_groups: ['triceps', 'chest', 'shoulders'],
    primary_muscle: 'triceps',
    secondary_muscles: ['chest', 'shoulders'],
    equipment: ['bodyweight'],
    is_compound: true,
    difficulty: 'intermediate',
    substitutes: ['close_grip_bench_press', 'tricep_pushdown', 'bench_dips'],
    instructions: 'Stay vertical with elbows tucked back to focus entirely on tricep extension.',
    instruction_details: {
      setup: 'Mount dip bars, keep torso completely upright with legs hanging straight down.',
      execution: 'Lower until upper arms are parallel to floor with elbows pointing straight back. Press up to lockout.',
      cues: ['Keep body vertical — do not lean forward', 'Keep elbows tucked in'],
    },
  },
  bench_dips: {
    id: 'bench_dips',
    name: 'Bench Dips',
    muscle_groups: ['triceps', 'shoulders'],
    primary_muscle: 'triceps',
    secondary_muscles: ['shoulders'],
    equipment: ['bodyweight'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['tricep_dips', 'tricep_pushdown'],
    instructions: 'Hands on bench behind back, lower hips down toward floor and press up through palms.',
    instruction_details: {
      setup: 'Sit on bench edge, place hands next to hips. Extend legs out in front.',
      execution: 'Lower hips down past bench edge until elbows reach 90°. Press up to lockout.',
      cues: ['Keep back close to bench', 'Lock triceps at the top'],
    },
  },
  cable_kickbacks: {
    id: 'cable_kickbacks',
    name: 'Single-Arm Cable Tricep Kickback',
    muscle_groups: ['triceps'],
    primary_muscle: 'triceps',
    equipment: ['cable'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['tricep_pushdown'],
    instructions: 'Hinged forward with no handle on cable wire for continuous tricep peak contraction.',
    instruction_details: {
      setup: 'Set cable at chest height without handle. Hinge forward at waist.',
      execution: 'Extend arm straight back behind hip. Squeeze tricep hard at full extension.',
      cues: ['Keep upper arm parallel to ground', 'Hold contraction for 1 second'],
    },
  },

  // ============================================================
  // LEGS — QUADS
  // ============================================================
  barbell_back_squat: {
    id: 'barbell_back_squat',
    name: 'Barbell Back Squat (High Bar / Low Bar)',
    muscle_groups: ['quads', 'glutes', 'hamstrings', 'core'],
    primary_muscle: 'quads',
    secondary_muscles: ['glutes', 'hamstrings', 'core', 'calves'],
    equipment: ['barbell'],
    is_compound: true,
    difficulty: 'intermediate',
    substitutes: ['barbell_front_squat', 'leg_press', 'goblet_squat', 'hack_squat'],
    instructions: 'The foundational lower body strength builder. Squat below parallel and drive upward.',
    instruction_details: {
      setup: 'Bar securely on upper traps (high bar) or rear delts (low bar). Feet shoulder-width with toes flared out 15-30°.',
      execution: 'Take deep diaphragmatic breath into belly and brace core. Sit down and back between thighs until hips drop below parallel. Drive up aggressively through midfoot.',
      cues: ['Knees track over toes', 'Keep chest proud and spine neutral', 'Drive through midfoot'],
    },
  },
  barbell_front_squat: {
    id: 'barbell_front_squat',
    name: 'Barbell Front Squat',
    muscle_groups: ['quads', 'core', 'glutes'],
    primary_muscle: 'quads',
    secondary_muscles: ['core', 'glutes'],
    equipment: ['barbell'],
    is_compound: true,
    difficulty: 'advanced',
    substitutes: ['barbell_back_squat', 'goblet_squat', 'hack_squat'],
    instructions: 'Bar resting across clavicle and front deltoids with high elbows for upright quad focus.',
    instruction_details: {
      setup: 'Clean grip or cross-arm grip with elbows held high parallel to ground. Feet shoulder-width.',
      execution: 'Squat down keeping torso strictly vertical. Descend into full depth, drive up through heels/midfoot.',
      cues: ['Keep elbows up high throughout', 'Torso completely upright', 'Maximum quad loading'],
    },
  },
  leg_press: {
    id: 'leg_press',
    name: '45-Degree Incline Leg Press',
    muscle_groups: ['quads', 'glutes', 'hamstrings'],
    primary_muscle: 'quads',
    secondary_muscles: ['glutes', 'hamstrings'],
    equipment: ['machine'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['barbell_back_squat', 'hack_squat', 'goblet_squat'],
    instructions: 'Heavy leg overload with zero spinal compression.',
    instruction_details: {
      setup: 'Back flat against seat, feet shoulder-width on platform at mid-height.',
      execution: 'Release safety handles. Lower sled until knees bend past 90°. Press platform back up without locking knees hard.',
      cues: ['Do not let lower back round off the pad', 'Do not aggressively hyperextend knees at top', 'Deep controlled depth'],
    },
  },
  hack_squat: {
    id: 'hack_squat',
    name: 'Hack Squat Machine',
    muscle_groups: ['quads', 'glutes'],
    primary_muscle: 'quads',
    secondary_muscles: ['glutes'],
    equipment: ['machine'],
    is_compound: true,
    difficulty: 'intermediate',
    substitutes: ['barbell_front_squat', 'leg_press', 'barbell_back_squat'],
    instructions: 'Angled machine squat for deep knee flexion and tear-drop quad growth.',
    instruction_details: {
      setup: 'Shoulders under pads, back flat against support pad. Feet mid-platform.',
      execution: 'Descend into full deep knee flexion. Push through midfoot to return to top.',
      cues: ['Keep back pressed against pad', 'Hit full quad stretch depth'],
    },
  },
  goblet_squat: {
    id: 'goblet_squat',
    name: 'Dumbbell / Kettlebell Goblet Squat',
    muscle_groups: ['quads', 'glutes', 'core'],
    primary_muscle: 'quads',
    secondary_muscles: ['glutes', 'core'],
    equipment: ['dumbbell', 'kettlebell'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['barbell_back_squat', 'leg_press'],
    instructions: 'Hold weight vertically against chest. Perfect for mobility and beginner squat mechanics.',
    instruction_details: {
      setup: 'Hold dumbbell vertically against upper chest with both hands. Feet shoulder-width apart.',
      execution: 'Squat down between knees until elbows touch inside of thighs. Stand back up.',
      cues: ['Chest tall against the weight', 'Spread knees apart on descent'],
    },
  },
  bulgarian_split_squat: {
    id: 'bulgarian_split_squat',
    name: 'Bulgarian Split Squat (Rear-Foot Elevated)',
    muscle_groups: ['quads', 'glutes', 'hamstrings'],
    primary_muscle: 'quads',
    secondary_muscles: ['glutes', 'hamstrings'],
    equipment: ['dumbbell', 'bodyweight'],
    is_compound: true,
    difficulty: 'intermediate',
    substitutes: ['walking_lunges', 'barbell_back_squat', 'leg_press'],
    instructions: 'Rear foot elevated on bench for intense single-leg quad and glute hypertrophy.',
    instruction_details: {
      setup: 'Place one foot back on bench surface. Front foot stepped forward 2-3 feet.',
      execution: 'Descend until back knee hovers 1 inch above floor. Drive through front heel to stand.',
      cues: ['Keep front shin relatively vertical for glutes, forward for quads', 'Drive through front heel'],
    },
  },
  walking_lunges: {
    id: 'walking_lunges',
    name: 'Dumbbell Walking Lunges',
    muscle_groups: ['quads', 'glutes', 'hamstrings', 'calves'],
    primary_muscle: 'quads',
    secondary_muscles: ['glutes', 'hamstrings'],
    equipment: ['dumbbell', 'bodyweight'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['bulgarian_split_squat', 'barbell_step_ups'],
    instructions: 'Step forward in alternating lunges, tapping back knee gently to floor each stride.',
    instruction_details: {
      setup: 'Hold dumbbells at sides with tall posture.',
      execution: 'Step forward into lunge, lowering hips until both knees are at 90°. Drive up through front heel into next stride.',
      cues: ['Take confident balanced steps', 'Keep torso upright', 'Do not slam knee into ground'],
    },
  },
  leg_extension: {
    id: 'leg_extension',
    name: 'Seated Machine Leg Extension',
    muscle_groups: ['quads'],
    primary_muscle: 'quads',
    equipment: ['machine'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['goblet_squat', 'hack_squat'],
    instructions: 'Pure quad isolation reaching peak contraction at full leg extension.',
    instruction_details: {
      setup: 'Adjust back pad so knees align with machine pivot axis. Shin pad sits right above ankles.',
      execution: 'Extend legs straight up. Hold peak quad flex for 1 full second. Lower smoothly over 3s.',
      cues: ['Do not swing weights', 'Hold peak squeeze at top for 1s', 'Control the descent'],
    },
  },

  // ============================================================
  // LEGS — HAMSTRINGS & GLUTES
  // ============================================================
  romanian_deadlift: {
    id: 'romanian_deadlift',
    name: 'Barbell Romanian Deadlift (RDL)',
    muscle_groups: ['hamstrings', 'glutes', 'back'],
    primary_muscle: 'hamstrings',
    secondary_muscles: ['glutes', 'back'],
    equipment: ['barbell'],
    is_compound: true,
    difficulty: 'intermediate',
    substitutes: ['dumbbell_rdl', 'lying_leg_curl', 'good_mornings'],
    instructions: 'Hinge hips backwards with soft knees to produce tremendous hamstring stretch and growth.',
    instruction_details: {
      setup: 'Stand tall holding barbell at hips with overhand grip. Soft knee bend.',
      execution: 'Push hips straight back like trying to touch a wall behind you. Lower bar down shins until hamstrings are fully stretched. Squeeze glutes to return.',
      cues: ['Hips back, not down', 'Keep bar shaving your legs', 'Stop when hips stop moving back'],
    },
  },
  dumbbell_rdl: {
    id: 'dumbbell_rdl',
    name: 'Dumbbell Romanian Deadlift (Dumbbell RDL)',
    muscle_groups: ['hamstrings', 'glutes', 'back'],
    primary_muscle: 'hamstrings',
    secondary_muscles: ['glutes', 'back'],
    equipment: ['dumbbell'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['romanian_deadlift', 'lying_leg_curl'],
    instructions: 'Dumbbells kept close to legs allow natural wrist orientation and deep hamstring stretch.',
    instruction_details: {
      setup: 'Hold dumbbells in front of thighs with slight knee bend.',
      execution: 'Hinge hips backward, lowering dumbbells to mid-shin level. Drive hips forward.',
      cues: ['Feel deep stretch in hamstrings', 'Keep back flat as a table'],
    },
  },
  hip_thrust: {
    id: 'hip_thrust',
    name: 'Barbell Hip Thrust',
    muscle_groups: ['glutes', 'hamstrings'],
    primary_muscle: 'glutes',
    secondary_muscles: ['hamstrings'],
    equipment: ['barbell'],
    is_compound: true,
    difficulty: 'intermediate',
    substitutes: ['dumbbell_glute_bridge', 'cable_pull_through', 'romanian_deadlift'],
    instructions: 'Upper back on bench, drive barbell up via hip extension for maximum glute peak force.',
    instruction_details: {
      setup: 'Upper back against bench edge (bra strap line). Barbell padded over hip crease. Feet flat on floor, shins vertical at top.',
      execution: 'Drive hips upward through heels until thighs and torso form a straight horizontal table. Squeeze glutes hard at top for 2s.',
      cues: ['Keep chin tucked to chest throughout', 'Drive through heels', 'Full glute lock at top'],
    },
  },
  lying_leg_curl: {
    id: 'lying_leg_curl',
    name: 'Lying Machine Leg Curl',
    muscle_groups: ['hamstrings'],
    primary_muscle: 'hamstrings',
    secondary_muscles: ['calves'],
    equipment: ['machine'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['seated_leg_curl', 'romanian_deadlift'],
    instructions: 'Lie prone, curl pad to glutes to train the knee flexion function of the hamstrings.',
    instruction_details: {
      setup: 'Knees aligned with machine pivot. Pad rests against lower calves/Achilles.',
      execution: 'Curl heels up towards glutes. Squeeze hamstrings at top and lower under 3-second control.',
      cues: ['Keep hips pressed down into the bench', 'Do not arch lower back', 'Full range of motion'],
    },
  },
  seated_leg_curl: {
    id: 'seated_leg_curl',
    name: 'Seated Machine Leg Curl',
    muscle_groups: ['hamstrings'],
    primary_muscle: 'hamstrings',
    equipment: ['machine'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['lying_leg_curl', 'romanian_deadlift'],
    instructions: 'Seated position places hamstrings on stretch at the hip for superior hypertrophy stimulus.',
    instruction_details: {
      setup: 'Back against pad, thigh clamp secured snugly. Heel pad on lower calves.',
      execution: 'Curl pad down and underneath seat. Hold for 1 sec and return under control.',
      cues: ['Greatest hamstring stretch at the top', 'Slow 3s return'],
    },
  },
  cable_glute_kickback: {
    id: 'cable_glute_kickback',
    name: 'Cable Glute Kickback',
    muscle_groups: ['glutes'],
    primary_muscle: 'glutes',
    equipment: ['cable'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['hip_thrust'],
    instructions: 'Ankle cuff attached to low cable, kick leg backward into hip extension.',
    instruction_details: {
      setup: 'Ankle strap on low pulley. Hold cable column with slight forward torso tilt.',
      execution: 'Kick leg back and slightly outward in a 45° angle. Squeeze glute at peak.',
      cues: ['Squeeze glute at top', 'Do not hyperextend lower back'],
    },
  },
  abductor_machine: {
    id: 'abductor_machine',
    name: 'Seated Machine Hip Abduction (Glute Medius)',
    muscle_groups: ['glutes'],
    primary_muscle: 'glutes',
    equipment: ['machine'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['cable_glute_kickback'],
    instructions: 'Push pads outward to target upper side glutes (glute medius & minimus).',
    instruction_details: {
      setup: 'Sit with back flat (or lean slightly forward) with outer knees against pads.',
      execution: 'Push knees open as wide as possible. Hold for 1 sec at maximum spread.',
      cues: ['Squeeze side glutes', 'Control the return'],
    },
  },

  // ============================================================
  // CALVES
  // ============================================================
  standing_calf_raise: {
    id: 'standing_calf_raise',
    name: 'Standing Machine / Barbell Calf Raise',
    muscle_groups: ['calves'],
    primary_muscle: 'calves',
    equipment: ['machine', 'barbell'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['seated_calf_raise', 'leg_press_calf_raise'],
    instructions: 'Straight-leg calf raises to heavily target the gastrocnemius (outer calf diamond).',
    instruction_details: {
      setup: 'Balls of feet on edge of platform, heels hanging off into full deep stretch.',
      execution: 'Rise all the way up onto big toes. Pause for 1 sec at top, then descend into 2-sec deep stretch at bottom.',
      cues: ['Full stretch at bottom — do not bounce', 'Press through the big toe ball', 'Hold peak contraction'],
    },
  },
  seated_calf_raise: {
    id: 'seated_calf_raise',
    name: 'Seated Machine Calf Raise (Soleus)',
    muscle_groups: ['calves'],
    primary_muscle: 'calves',
    equipment: ['machine'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['standing_calf_raise'],
    instructions: 'Bent knee position isolates the deep soleus muscle that widens the lower leg.',
    instruction_details: {
      setup: 'Sit with knees bent at 90° under thigh pad. Balls of feet on platform.',
      execution: 'Lower heels into deep stretch, then elevate onto toes as high as possible.',
      cues: ['Hold deep stretch at bottom for 2 seconds', 'Full range of motion'],
    },
  },
  leg_press_calf_raise: {
    id: 'leg_press_calf_raise',
    name: 'Leg Press Calf Raise (Toe Press)',
    muscle_groups: ['calves'],
    primary_muscle: 'calves',
    equipment: ['machine'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['standing_calf_raise'],
    instructions: 'Balls of feet on bottom lip of leg press sled, extend ankles forward.',
    instruction_details: {
      setup: 'Legs straight with soft knees on leg press. Balls of feet on bottom edge.',
      execution: 'Push sled forward with toes. Let sled push heels back into full stretch.',
      cues: ['Keep knees soft — never lock them out completely', 'Deep controlled stretch'],
    },
  },

  // ============================================================
  // CORE & ABDOMINALS
  // ============================================================
  hanging_leg_raise: {
    id: 'hanging_leg_raise',
    name: 'Hanging Leg Raise (Toes to Bar / Knees to Chest)',
    muscle_groups: ['core', 'forearms'],
    primary_muscle: 'core',
    secondary_muscles: ['forearms'],
    equipment: ['bodyweight', 'pull_up_bar'],
    is_compound: true,
    difficulty: 'intermediate',
    substitutes: ['ab_wheel_rollout', 'cable_crunch', 'decline_crunch'],
    instructions: 'Hang from pull-up bar and curl pelvis up bringing feet or knees to chest level.',
    instruction_details: {
      setup: 'Hang from pull-up bar with overhand grip. Posterior pelvic tilt.',
      execution: 'Raise legs up by rounding the pelvis upward toward chest. Lower under control without swinging.',
      cues: ['Curl pelvis toward ribs — do not just swing hip flexors', 'No swinging momentum', 'Exhale hard at top'],
    },
  },
  cable_crunch: {
    id: 'cable_crunch',
    name: 'Kneeling Cable Rope Crunch',
    muscle_groups: ['core'],
    primary_muscle: 'core',
    equipment: ['cable'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['hanging_leg_raise', 'decline_crunch', 'ab_wheel_rollout'],
    instructions: 'Kneel holding rope beside ears, curl ribcage down toward pelvis.',
    instruction_details: {
      setup: 'Kneel in front of high cable with rope handles held right at temples/ears. Hips stay locked in place.',
      execution: 'Flex spine and crunch ribcage down toward your thighs. Squeeze abs hard at bottom.',
      cues: ['Do not sit back onto heels', 'Curl spine like a shrimp', 'Exhale completely at the crunch'],
    },
  },
  ab_wheel_rollout: {
    id: 'ab_wheel_rollout',
    name: 'Ab Wheel Rollout',
    muscle_groups: ['core', 'shoulders', 'back'],
    primary_muscle: 'core',
    secondary_muscles: ['shoulders', 'back'],
    equipment: ['bodyweight'],
    is_compound: true,
    difficulty: 'intermediate',
    substitutes: ['hanging_leg_raise', 'cable_crunch', 'plank'],
    instructions: 'Kneel and roll the wheel forward until body is near horizontal, then pull back via core flexion.',
    instruction_details: {
      setup: 'Kneel on pad, grip ab wheel handles under shoulders.',
      execution: 'Roll wheel forward into a straight line keeping core braced and hips extended. Pull wheel back with abs.',
      cues: ['Do not let lower back sag or arch', 'Tuck pelvis under', 'Pull back with abdominals'],
    },
  },
  plank: {
    id: 'plank',
    name: 'Front Forearm Plank (Anti-Extension)',
    muscle_groups: ['core', 'shoulders', 'glutes'],
    primary_muscle: 'core',
    secondary_muscles: ['shoulders', 'glutes'],
    equipment: ['bodyweight'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['ab_wheel_rollout', 'dead_bug'],
    instructions: 'Isometric core stability hold with elbows under shoulders and rigid full-body tension.',
    instruction_details: {
      setup: 'Rest on forearms and toes. Elbows directly beneath shoulders.',
      execution: 'Clench glutes, pull belly button in, and hold rock-solid straight line.',
      cues: ['Create maximum full-body tension', 'Do not let hips sag or hike up'],
    },
  },
  russian_twists: {
    id: 'russian_twists',
    name: 'Seated Russian Twists (Obliques)',
    muscle_groups: ['core'],
    primary_muscle: 'core',
    equipment: ['bodyweight', 'dumbbell'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['cable_woodchopper'],
    instructions: 'V-sit position rotating torso side to side with dumbbell or medicine ball.',
    instruction_details: {
      setup: 'Sit on floor, lean back 45°, elevate feet slightly. Hold weight at chest.',
      execution: 'Rotate torso fully to right, touch floor, then rotate to left.',
      cues: ['Rotate with shoulders and ribcage, not just arms', 'Keep core braced'],
    },
  },
  cable_woodchopper: {
    id: 'cable_woodchopper',
    name: 'Cable Woodchopper (High-to-Low / Low-to-High)',
    muscle_groups: ['core', 'shoulders'],
    primary_muscle: 'core',
    secondary_muscles: ['shoulders'],
    equipment: ['cable'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['russian_twists'],
    instructions: 'Diagonal rotational movement developing athletic core power and oblique definition.',
    instruction_details: {
      setup: 'Stand sideways to cable stack holding handle with both hands in athletic stance.',
      execution: 'Rotate torso diagonally across body in a chopping motion. Pivot back foot.',
      cues: ['Power comes from hips and core rotation', 'Keep arms mostly straight'],
    },
  },
  decline_crunch: {
    id: 'decline_crunch',
    name: 'Decline Bench Abdominal Crunch',
    muscle_groups: ['core'],
    primary_muscle: 'core',
    equipment: ['bodyweight', 'dumbbell'],
    is_compound: false,
    difficulty: 'beginner',
    substitutes: ['cable_crunch', 'hanging_leg_raise'],
    instructions: 'Hook legs in decline bench, curl upper body up against gravity.',
    instruction_details: {
      setup: 'Lock feet in decline bench. Cross arms over chest or hold weight plate.',
      execution: 'Curl torso up by flexing abdominal wall. Pause at top, lower slowly.',
      cues: ['Round spine on the way up', 'Do not pull on neck'],
    },
  },

  // ============================================================
  // CARDIO & FUNCTIONAL / FULL BODY
  // ============================================================
  incline_treadmill: {
    id: 'incline_treadmill',
    name: 'Incline Treadmill Power Walk (Zone 2)',
    muscle_groups: ['cardio', 'calves', 'glutes'],
    primary_muscle: 'cardio',
    secondary_muscles: ['calves', 'glutes'],
    equipment: ['cardio_machine'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['stair_climber', 'stationary_bike', 'rowing_ergometer'],
    instructions: '12-15% incline at 3-3.5 mph for low-impact joint-friendly fat oxidation.',
    instruction_details: {
      setup: 'Set treadmill to 12% to 15% incline. Speed 3.0 to 3.5 mph.',
      execution: 'Walk with tall posture without holding onto handrails for pure core/leg work.',
      cues: ['Do not hold handrails', 'Breathe through nose in Zone 2', 'Drive with glutes and calves'],
    },
  },
  stair_climber: {
    id: 'stair_climber',
    name: 'Stair Climber (StairMaster)',
    muscle_groups: ['cardio', 'glutes', 'calves', 'quads'],
    primary_muscle: 'cardio',
    secondary_muscles: ['glutes', 'calves', 'quads'],
    equipment: ['cardio_machine'],
    is_compound: true,
    difficulty: 'intermediate',
    substitutes: ['incline_treadmill', 'rowing_ergometer'],
    instructions: 'Continuous stepping movement heavily targeting glutes, calves, and cardiovascular capacity.',
    instruction_details: {
      setup: 'Select steady pace level (level 6-10).',
      execution: 'Step fully onto each step with whole foot. Push through heels to engage glutes.',
      cues: ['Do not lean heavily on handrails', 'Step with full foot, not just toes'],
    },
  },
  rowing_ergometer: {
    id: 'rowing_ergometer',
    name: 'Concept2 Rowing Ergometer',
    muscle_groups: ['cardio', 'back', 'legs', 'core'],
    primary_muscle: 'cardio',
    secondary_muscles: ['back', 'legs', 'core'],
    equipment: ['cardio_machine'],
    is_compound: true,
    difficulty: 'intermediate',
    substitutes: ['incline_treadmill', 'assault_bike'],
    instructions: 'Full-body cardiovascular conditioning: Drive with legs (60%), swing with hips (20%), pull with arms (20%).',
    instruction_details: {
      setup: 'Feet strapped securely. Grab handle overhand, arms straight, knees bent.',
      execution: 'Explosively push with legs, hinge torso back, then pull handle to lower ribs.',
      cues: ['Legs, Core, Arms on the drive', 'Arms, Core, Legs on the recovery'],
    },
  },
  assault_bike: {
    id: 'assault_bike',
    name: 'Assault Air Bike (HIIT Sprints)',
    muscle_groups: ['cardio', 'legs', 'shoulders', 'full_body'],
    primary_muscle: 'cardio',
    secondary_muscles: ['legs', 'shoulders'],
    equipment: ['cardio_machine'],
    is_compound: true,
    difficulty: 'intermediate',
    substitutes: ['rowing_ergometer', 'jump_rope'],
    instructions: 'Total-body sprint interval tool using push/pull arm action and intense leg pedaling.',
    instruction_details: {
      setup: 'Adjust seat so knee has slight bend at bottom of pedal stroke.',
      execution: 'Push and pull handles aggressively while driving through pedals at maximum output.',
      cues: ['High-intensity sprint intervals (e.g. 20s sprint / 40s rest)'],
    },
  },
  jump_rope: {
    id: 'jump_rope',
    name: 'Jump Rope (Speed Rope)',
    muscle_groups: ['cardio', 'calves', 'forearms', 'shoulders'],
    primary_muscle: 'cardio',
    secondary_muscles: ['calves', 'forearms'],
    equipment: ['bodyweight'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['incline_treadmill'],
    instructions: 'Agile bouncing on the balls of feet with quick wrist rotations.',
    instruction_details: {
      setup: 'Rope sized so handles reach armpits when standing on middle.',
      execution: 'Jump lightly 1-2 inches off floor. Rotate rope purely with wrists.',
      cues: ['Stay light on balls of feet', 'Turn with wrists, not whole arms'],
    },
  },
  kettlebell_swings: {
    id: 'kettlebell_swings',
    name: 'Russian Kettlebell Swings',
    muscle_groups: ['glutes', 'hamstrings', 'back', 'core', 'cardio'],
    primary_muscle: 'glutes',
    secondary_muscles: ['hamstrings', 'back', 'core'],
    equipment: ['kettlebell'],
    is_compound: true,
    difficulty: 'intermediate',
    substitutes: ['romanian_deadlift', 'conventional_deadlift'],
    instructions: 'Explosive hip hinge driving kettlebell to chest level via glute snap.',
    instruction_details: {
      setup: 'Stand over kettlebell with wide stance. Hinge at hips and grab handle.',
      execution: 'Hike bell between legs, then snap hips forward explosively to propel bell to chest level.',
      cues: ['It is a hip hinge, not a squat', 'Snap glutes at the top', 'Arms are just ropes'],
    },
  },
  farmers_walk: {
    id: 'farmers_walk',
    name: 'Farmer\'s Walk (Heavy Dumbbell Carry)',
    muscle_groups: ['forearms', 'traps', 'core', 'legs'],
    primary_muscle: 'forearms',
    secondary_muscles: ['traps', 'core', 'legs'],
    equipment: ['dumbbell', 'kettlebell'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['barbell_shrugs'],
    instructions: 'Pick up heavy weights and walk with tall posture and rigid core.',
    instruction_details: {
      setup: 'Deadlift two heavy dumbbells or kettlebells to sides.',
      execution: 'Walk forward with short, fast, controlled steps maintaining upright spine.',
      cues: ['Chest up, shoulders back', 'Do not let weights swing', 'Crush handles with grip'],
    },
  },
  burpees: {
    id: 'burpees',
    name: 'Full Body Burpees',
    muscle_groups: ['cardio', 'chest', 'legs', 'core', 'full_body'],
    primary_muscle: 'cardio',
    secondary_muscles: ['chest', 'legs', 'core'],
    equipment: ['bodyweight'],
    is_compound: true,
    difficulty: 'beginner',
    substitutes: ['jump_rope', 'kettlebell_swings'],
    instructions: 'Drop into push-up on floor, jump feet in, and jump up clapping hands overhead.',
    instruction_details: {
      setup: 'Stand with feet shoulder-width apart.',
      execution: 'Squat down, place hands on floor, kick feet back into push-up, touch chest to floor, jump feet forward and jump up with hands overhead.',
      cues: ['Smooth continuous rhythm', 'Land softly on balls of feet'],
    },
  },
}

// ─── Utility Helper Functions ──────────────────────────────────

/**
 * Filter exercises by muscle group
 */
export function getExercisesByMuscle(muscle: MuscleGroup): Exercise[] {
  return Object.values(EXERCISES).filter(
    (ex) => ex.primary_muscle === muscle || ex.muscle_groups.includes(muscle)
  )
}

/**
 * Filter exercises by equipment
 */
export function getExercisesByEquipment(equipment: EquipmentRequired): Exercise[] {
  return Object.values(EXERCISES).filter((ex) => ex.equipment.includes(equipment))
}

/**
 * Search exercises by query string across name, muscles, and equipment
 */
export function searchExercises(query: string, customList: Exercise[] = []): Exercise[] {
  const q = query.trim().toLowerCase()
  const all = [...Object.values(EXERCISES), ...customList]
  if (!q) return all

  return all.filter((ex) => {
    return (
      ex.name.toLowerCase().includes(q) ||
      ex.muscle_groups.some((m) => m.toLowerCase().includes(q)) ||
      ex.equipment.some((eq) => eq.toLowerCase().includes(q)) ||
      (ex.instructions && ex.instructions.toLowerCase().includes(q))
    )
  })
}

/**
 * Find the best equipment-compatible substitute for an exercise
 */
export function getBestSubstitute(
  exercise: Exercise,
  availableEquipment: EquipmentType
): Exercise {
  const allowed = EQUIPMENT_MAP[availableEquipment] ?? ['barbell', 'dumbbell', 'cable', 'machine', 'bodyweight']

  // If exercise equipment is already allowed, return it
  if (exercise.equipment.some((eq) => allowed.includes(eq))) {
    return exercise
  }

  // Look through listed substitutes
  if (exercise.substitutes) {
    for (const subId of exercise.substitutes) {
      const sub = EXERCISES[subId]
      if (sub && sub.equipment.some((eq) => allowed.includes(eq))) {
        return sub
      }
    }
  }

  // Find any exercise targeting the same primary muscle with allowed equipment
  const fallback = Object.values(EXERCISES).find(
    (e) =>
      e.id !== exercise.id &&
      (e.primary_muscle === exercise.primary_muscle || e.muscle_groups.some((m) => exercise.muscle_groups.includes(m))) &&
      e.equipment.some((eq) => allowed.includes(eq))
  )

  return fallback ?? exercise
}

const EQUIPMENT_MAP: Record<EquipmentType, EquipmentRequired[]> = {
  full_gym: ['barbell', 'dumbbell', 'cable', 'machine', 'bodyweight', 'kettlebell', 'resistance_band', 'pull_up_bar', 'smith_machine', 'cardio_machine'],
  home_gym: ['barbell', 'dumbbell', 'bodyweight', 'kettlebell', 'resistance_band', 'pull_up_bar'],
  dumbbells: ['dumbbell', 'bodyweight', 'resistance_band'],
  bodyweight: ['bodyweight', 'pull_up_bar', 'resistance_band'],
}
